db_mellitus/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('diagnose/<int:pk>', views.dm_prediction, name='diagnose-patient'),
    path('patient-list/', views.patient_list, name='patient-list'),
    path('view/<int:pk>', views.patient_view, name='patient-view'),
    path('new/', views.patient_create, name='patient-new'),
    path('edit/<int:pk>', views.patient_update, name='patient-edit'),
    path('delete/<int:pk>', views.patient_delete, name='patient-delete'),
]

mellitus_db/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('db_mellitus.urls')),
]

db_mellitus/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
GENDER = [
    ('M', 'Male'),
    ('F', 'Female')
]


class Symptom(models.Model):
    pregnancy_count = models.IntegerField(blank=False)
    plasma = models.IntegerField(blank=False)
    skin_thickness = models.IntegerField(blank=False)
    blood_pressure = models.IntegerField(blank=False)
    insulin = models.IntegerField(blank=False)
    bmi = models.FloatField(blank=False)
    pedigree = models.FloatField(blank=False)
    age = models.IntegerField(blank=False)
    prediction_result = models.BooleanField(default=False, blank=True)
    type_one_result = models.BooleanField(default=False, blank=True)
    type_two_result = models.BooleanField(default=False, blank=True)
    gestational_result = models.BooleanField(default=False, blank=True)

    def __int__(self):
        return Symptom.age


class Patient(models.Model):
    first_name = models.CharField(max_length=10, blank=False)
    middle_name = models.CharField(max_length=10, blank=False)
    last_name = models.CharField(max_length=10, blank=False)
    dob = models.DateField(blank=False)
    gender = models.CharField(max_length=1, choices=GENDER, blank=False)
    symptom = models.OneToOneField(Symptom, on_delete=models.CASCADE, blank=True)

    def get_absolute_url(self):
        return reverse('patient-edit', kwargs={'pk': self.pk})

db_mellitus/forms.py
from django import formsfrom .models import  Patient, Symptomclass RegisterPatientForm(forms.ModelForm):    class Meta:        model = Patient        fields = ('first_name', 'middle_name', 'last_name', 'dob', 'gender', )        #exclude = ( '__symptom__',)class SymptomForm(forms.ModelForm):    class Meta:        model = Symptom        fields = '__all__'

db_mellitus/views.py
from .forms import RegisterPatientForm
from django.shortcuts import render, redirect, get_object_or_404
from .models import Patient, Symptom
from django.core.paginator import Paginator
from django.views.decorators.http import require_http_methods
import numpy as np
import joblib

# Create your views here.


@require_http_methods(["GET", "POST"])
def patient_create(request):
    print(request)
    person = Patient()
    person.first_name = request.POST.get('first_name')
    person.middle_name = request.POST.get('middle_name')
    person.last_name = request.POST.get('last_name')
    person.dob = request.POST.get('dob')
    person.gender = request.POST.get('gender')
    person.save()
    return render(request, 'patient/patient-form.html')


def patient_list(request, template_name='patient/patient-list.html'):
    # noinspection PyUnresolvedReferences
    patient = Patient.objects.all()
    paginator = Paginator(patient, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, template_name, {'object_list': patient, 'page_obj': page_obj})


@require_http_methods(["POST", "GET"])
def patient_update(request, pk, template_name='patient/patient-edit.html'):
    person = get_object_or_404(Patient, pk=pk)
    person.first_name = request.POST.get('first_name')
    person.middle_name = request.POST.get('middle_name')
    person.last_name = request.POST.get('last_name')
    person.dob = request.POST.get('dob')
    person.gender = request.POST.get('gender')
    person.save()
    context = {
        'object': person
    }
    return render(request, template_name, {'object': person})


@require_http_methods(["GET", "POST"])
def patient_delete(request, pk, template_name='patient/patient-confirm-delete.html'):
    patient = get_object_or_404(Patient, pk=pk)
    if request.method == 'POST':
        patient.delete()
        return redirect('patient-list')
    return render(request, template_name, {'object': patient})


def patient_view(request, pk, template_name='patient/patient-detail.html'):
    patient = get_object_or_404(Patient, pk=pk)
    return render(request, template_name, {'object': patient})


@require_http_methods(["GET", "POST"])
def dm_prediction(request, pk):
    symptom = get_object_or_404(Patient, pk=pk)
    symptom.pregnancy_count = request.POST.get("pregnancy_count")
    symptom.plasma = request.POST.get("plasma")
    symptom.blood_pressure = request.POST.get("blood_pressure")
    symptom.skin_thickness = request.POST.get("skin_thickness")
    symptom.insulin = request.POST.get("insulin")
    symptom.bmi = request.POST.get("bmi")
    symptom.pedigree = request.POST.get("pedigree")
    symptom.age = request.POST.get("age")

    user_data = np.array(
        [
            [
                symptom.pregnancy_count, symptom.plasma,
                symptom.blood_pressure, symptom.skin_thickness,
                symptom.insulin, symptom.bmi,
                symptom.pedigree, symptom.age
            ]
        ]
    ).reshape(1, 8)

    model_path = 'ml_model/model.pkl'
    svc = joblib.load(open(model_path, 'rb'))
    prediction = svc.predict(user_data)

    symptom.prediction_result = prediction[0]
    symptom.save()

    context = {
        'patient': symptom
    }

    return render(request, "patient/diagnose.html", context)

db_mellitus/templates/patient/patient-edit.html
<!DOCTYPE html>

<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'scss/_mixin.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_responsive.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_variables.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_theme_color.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/style.scss' %}">

    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Diabetics - Melitus Know Your Status</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Style CSS -->

</head>

<body>

<style>

    body{
      font-family: Berlin Sans FB;
    }
    .select {
    font-size: 14px;
    padding: 10px;
    display: block;
    width: 100%;
    height: 35px;
    border: none;
    border-bottom: 2px solid;
    border-color: #f1f1f1;
    }
</style>
    <!-- Preloader Start -->
    <div id="preloader">
        <div class="preload-content">
            <div id="world-load"></div>
        </div>
    </div>
    <!-- Preloader End -->

    <!-- ***** Header Area Start ***** -->
    <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-lg">
                        <!-- Logo -->
                        <a class="navbar-brand" href="index.html"><img src="{% static 'img/core-img/logo.png' %}" alt="Logo"></a>
                        <!-- Navbar Toggler -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#worldNav" aria-controls="worldNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <!-- Navbar -->
                        <div class="collapse navbar-collapse" id="worldNav">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pages</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="index.html">Home</a>
                                        <a class="dropdown-item" href="catagory.html">Catagory</a>
                                        <a class="dropdown-item" href="single-blog.html">Single Blog</a>
                                        <a class="dropdown-item" href="regular-page.html">Regular Page</a>
                                        <a class="dropdown-item" href="contact.html">Contact</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#"><span class="glyphicon glyphicon-home"></span> Gadgets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'patient-list' %}"><span class="glyphicon glyphicon-envelope"></span> patient list</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% static 'url' %}"><span class="glyphicon glyphicon-bell"></span> Notifications </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-eye-close"></span> LogOut</a>
                                </li>
                            </ul>
                            <!-- Search Form  -->
                            <div id="search-wrapper">
                                <form action="#">
                                    <input type="text" id="search" placeholder="Search something...">
                                    <div id="close-icon"></div>
                                    <input class="d-none" type="submit" value="">
                                </form>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ********** Hero Area Start ********** -->
    <div class="hero-area height-400 bg-img background-overlay" style="background-image: url(/static/img/blog-img/bg4.jpg);"></div>
    <!-- ********** Hero Area End ********** -->

    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Contact Form Area -->
                <div class="col-12 col-md-10 col-lg-8">
                    <div class="contact-form">
                        <h5>PATIENT EDIT</h5><hr>
                        <!-- Contact Form -->
                        <form action="{% url 'patient-edit' pk %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-3">
                                    <label>First Name</label>
                                    <div class="group">
                                        <input type="text" name="first_name" id="f_name" value={{object.first_name}} required>
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                                <div class="col-6">
                                     <label>Middle Name</label>
                                    <div class="group">
                                        <input type="text" name="middle_name" id="m_name" value={{object.middle_name}} required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-6">
                                     <label>Last Name</label>
                                    <div class="group">
                                        <input type="text" name="last_name" id="l_name" value={{object.last_name}} required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                  <div class="col-6">
                                    <div class="group">
                                        <input type="date" name="age" id="age" value={{object.dob}} required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-6">
                                     <label>Sex</label>
                                    <div class="group">
                                        <select name="gender" class="select form-control" required="" id="id_gender" style="width:20%;">
                                            <option value="" selected="">{{object.gender}}</option>
                                            <option value="M">Male</option>
                                            <option value="F">Female</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <input type="submit" class="btn btn-success" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Google Maps: If you want to google map, just uncomment below codes -->
    <!--
    <div class="map-area">
        <div id="googleMap" class="googleMap"></div>
    </div>
    -->

    <!-- ***** Footer Area Start ***** -->
        <footer class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4">
                    <div class="footer-single-widget">
                        <a href="#"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                        <div class="copywrite-text mt-30">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This application is developed <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Stephen</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>

                <div class="col-12 col-md-4">
                    <div class="footer-single-widget">
                        <h5>Subscribe</h5>
                        <form action="#" method="post">
                            <input type="email" name="email" id="email" placeholder="Enter your mail">
                            <button type="button"><i class="fa fa-arrow-right"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
    <!-- Google Maps: If you want to google map, just uncomment below codes -->
    <!--
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwuyLRa1uKNtbgx6xAJVmWy-zADgegA2s"></script>
    <script src="js/map-active.js"></script>
    -->

</body>

</html>

db_mellitus/templates/patient/patient-form.html
<!DOCTYPE html>

<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'scss/_mixin.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_responsive.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_variables.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/_theme_color.scss' %}">
    <link rel="stylesheet" href="{% static 'scss/style.scss' %}">

    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Diabetics - Melitus Know Your Status</title>

    <!-- Favicon  -->
    <link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">

    <!-- Style CSS -->

</head>

<body>

<style>

    body, h5{
    font-family: sans-serif;
    }
    .select {
    font-size: 14px;
    padding: 10px;
    display: block;
    width: 100%;
    height: 35px;
    border: none;
    border-bottom: 2px solid;
    border-color: #f1f1f1;
    }
</style>
    <!-- Preloader Start -->
    <div id="preloader">
        <div class="preload-content">
            <div id="world-load"></div>
        </div>
    </div>
    <!-- Preloader End -->

    <!-- ***** Header Area Start ***** -->
    <header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="navbar navbar-expand-lg">
                        <!-- Logo -->
                        <a class="navbar-brand" href="index.html"><img src="{% static 'img/core-img/logo.png' %}" alt="Logo"></a>
                        <!-- Navbar Toggler -->
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#worldNav" aria-controls="worldNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                        <!-- Navbar -->
                        <div class="collapse navbar-collapse" id="worldNav">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pages</a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="index.html">Home</a>
                                        <a class="dropdown-item" href="catagory.html">Catagory</a>
                                        <a class="dropdown-item" href="single-blog.html">Single Blog</a>
                                        <a class="dropdown-item" href="regular-page.html">Regular Page</a>
                                        <a class="dropdown-item" href="contact.html">Contact</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#"><span class="glyphicon glyphicon-home"></span> Gadgets</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'patient-list' %}"><span class="glyphicon glyphicon-envelope"></span> patient list</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% static 'url' %}"><span class="glyphicon glyphicon-bell"></span> Notifications </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a>
                                </li>
                            </ul>
                            <!-- Search Form  -->
                            <div id="search-wrapper">
                                <form action="#">
                                    <input type="text" id="search" placeholder="Search something...">
                                    <div id="close-icon"></div>
                                    <input class="d-none" type="submit" value="">
                                </form>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ********** Hero Area Start ********** -->
    <div class="hero-area height-400 bg-img background-overlay" style="background-image: url(/static/img/blog-img/bg4.jpg);"></div>
    <!-- ********** Hero Area End ********** -->

    <section class="contact-area section-padding-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Contact Form Area -->
                <div class="col-12 col-md-10 col-lg-8">
                    <div class="contact-form" style="font-family: ubuntu;">
                        <h5 style="font-family: ubuntu;">PATIENT REGISTRATION</h5><hr>
                        <!-- Contact Form -->

                        <form action="." method='post'>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-3">
                                    <label>First Name</label>
                                    <div class="group">
                                        <input type="text" name="first_name" id="f_name" required>
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-6">
                                     <label>Middle Name</label>
                                    <div class="group">
                                        <input type="text" name="middle_name" id="m_name" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-6">
                                     <label>Last Name</label>
                                    <div class="group">
                                        <input type="text" name="last_name" id="l_name" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                  <div class="col-6">
                                    <div class="group">
                                        <input type="date" name="dob" id="age" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-6">
                                     <label>Sex</label>
                                    <div class="group">
                                        <select name="gender" class="select form-control" required="" id="id_gender" style="width:20%;">
                                            <option value="" selected="">---------</option>
                                            <option value="M">Male</option>
                                            <option value="F">Female</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button type="submit" id="btn" class="btn btn-success">Register</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Google Maps: If you want to google map, just uncomment below codes -->
    <!--
    <div class="map-area">
        <div id="googleMap" class="googleMap"></div>
    </div>
    -->

    <!-- ***** Footer Area Start ***** -->
        <footer class="footer-area">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-12">
                    <div class="footer-single-widget">
                        <a href="#"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
                        <div class="copywrite-text mt-30">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This application is developed <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Stephen</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->

    <!-- jQuery (Necessary for All JavaScript Plugins) -->
    <script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
    <!-- Google Maps: If you want to google map, just uncomment below codes -->
    <!--
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwuyLRa1uKNtbgx6xAJVmWy-zADgegA2s"></script>
    <script src="js/map-active.js"></script>
    -->

</body>


</html>